/*
# Create FLUX shared backend schema

1. New Tables
- `users_user`: Django-compatible user records, including email, name, role, contact details, and password state.
- `groups_group`: savings groups, contribution rules, invite codes, and lifecycle status.
- `groups_membership`: the relationship between users and savings groups.
- `finances_request`: contribution, investment, and loan-related requests.
- `finances_record`: official contribution records.
- `finances_loan`: loan applications and repayment progress.
- `finances_goal`: personal savings goals with optional group links.

2. Security
- Row Level Security is enabled on every table.
- No browser-facing policies are added. Access is deny-by-default until the Django backend is connected with a server-side database role.
- Role, password, approval, repayment, and audit fields are not exposed for anonymous browser writes.

3. Important Notes
- Tables use the field names and relationships expected by the existing Django backend.
- This migration does not delete or alter existing user data.
- The backend must use a private database connection; the anon key must never be used for these tables.
*/

CREATE TABLE IF NOT EXISTS public.users_user (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  password varchar(128) NOT NULL,
  last_login timestamptz,
  is_superuser boolean NOT NULL DEFAULT false,
  username varchar(150) NOT NULL UNIQUE,
  first_name varchar(150) NOT NULL DEFAULT '',
  last_name varchar(150) NOT NULL DEFAULT '',
  is_staff boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  date_joined timestamptz NOT NULL DEFAULT now(),
  email varchar(254) NOT NULL UNIQUE,
  phone varchar(20) NOT NULL DEFAULT '',
  role varchar(20) NOT NULL DEFAULT 'member' CHECK (role IN ('sysadmin','chair','treasury','secretary','audit','mobilizer','member')),
  avatar varchar(10) NOT NULL DEFAULT '',
  must_change_password boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.groups_group (
  id varchar(50) PRIMARY KEY,
  name varchar(255) NOT NULL,
  description text NOT NULL DEFAULT '',
  contribution numeric(12,2) NOT NULL,
  frequency varchar(50) NOT NULL DEFAULT 'Monthly',
  cycle varchar(50) NOT NULL DEFAULT 'OPEN',
  invite_code varchar(50) UNIQUE,
  rules jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.groups_membership (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users_user(id) ON DELETE CASCADE,
  group_id varchar(50) NOT NULL REFERENCES public.groups_group(id) ON DELETE CASCADE,
  role varchar(50) NOT NULL DEFAULT 'member',
  joined_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.finances_request (
  id varchar(50) PRIMARY KEY,
  group_id varchar(50) NOT NULL REFERENCES public.groups_group(id) ON DELETE CASCADE,
  requester_id bigint NOT NULL REFERENCES public.users_user(id) ON DELETE CASCADE,
  type varchar(50) NOT NULL,
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  title varchar(255) NOT NULL DEFAULT '',
  method varchar(100) NOT NULL DEFAULT '',
  note text NOT NULL DEFAULT '',
  status varchar(50) NOT NULL DEFAULT 'pending',
  receipt_url varchar(500) NOT NULL DEFAULT '',
  votes jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  decided_at timestamptz,
  decided_by varchar(255) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.finances_record (
  id varchar(50) PRIMARY KEY,
  group_id varchar(50) NOT NULL REFERENCES public.groups_group(id) ON DELETE CASCADE,
  member_id bigint NOT NULL REFERENCES public.users_user(id) ON DELETE CASCADE,
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  method varchar(100) NOT NULL DEFAULT 'Unknown',
  note text NOT NULL DEFAULT '',
  receipt_url varchar(500) NOT NULL DEFAULT '',
  date timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.finances_loan (
  id varchar(50) PRIMARY KEY,
  group_id varchar(50) NOT NULL REFERENCES public.groups_group(id) ON DELETE CASCADE,
  requester_id bigint NOT NULL REFERENCES public.users_user(id) ON DELETE CASCADE,
  title varchar(255) NOT NULL,
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  interest_rate numeric(5,2) NOT NULL DEFAULT 0 CHECK (interest_rate >= 0),
  type varchar(50) NOT NULL DEFAULT 'Flat Rate',
  installments integer NOT NULL DEFAULT 1 CHECK (installments > 0),
  frequency varchar(20) NOT NULL DEFAULT 'Monthly',
  start_date varchar(100) NOT NULL DEFAULT '',
  reason text NOT NULL DEFAULT '',
  repaid numeric(12,2) NOT NULL DEFAULT 0 CHECK (repaid >= 0),
  status varchar(30) NOT NULL DEFAULT 'pending_secretary',
  created_at timestamptz NOT NULL DEFAULT now(),
  decided_at timestamptz,
  decided_by varchar(255) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS public.finances_goal (
  id varchar(50) PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users_user(id) ON DELETE CASCADE,
  linked_group_id varchar(50) REFERENCES public.groups_group(id) ON DELETE SET NULL,
  title varchar(255) NOT NULL,
  target_amount numeric(12,2) NOT NULL CHECK (target_amount >= 0),
  saved_amount numeric(12,2) NOT NULL DEFAULT 0 CHECK (saved_amount >= 0),
  target_date date NOT NULL,
  notes text NOT NULL DEFAULT '',
  status varchar(20) NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  decided_at timestamptz,
  decided_by varchar(255) NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS groups_membership_user_id_idx ON public.groups_membership(user_id);
CREATE INDEX IF NOT EXISTS groups_membership_group_id_idx ON public.groups_membership(group_id);
CREATE INDEX IF NOT EXISTS finances_request_group_id_idx ON public.finances_request(group_id);
CREATE INDEX IF NOT EXISTS finances_request_requester_id_idx ON public.finances_request(requester_id);
CREATE INDEX IF NOT EXISTS finances_record_group_id_idx ON public.finances_record(group_id);
CREATE INDEX IF NOT EXISTS finances_record_member_id_idx ON public.finances_record(member_id);
CREATE INDEX IF NOT EXISTS finances_loan_group_id_idx ON public.finances_loan(group_id);
CREATE INDEX IF NOT EXISTS finances_loan_requester_id_idx ON public.finances_loan(requester_id);
CREATE INDEX IF NOT EXISTS finances_goal_user_id_idx ON public.finances_goal(user_id);
CREATE INDEX IF NOT EXISTS finances_goal_linked_group_id_idx ON public.finances_goal(linked_group_id);

ALTER TABLE public.users_user ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.groups_group ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.groups_membership ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finances_request ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finances_record ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finances_loan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finances_goal ENABLE ROW LEVEL SECURITY;
